// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW2xcmw1fHO0Ez_ArxR7uduzHsWCiGHSs',
    appId: '1:17739122534:web:3eaa8cac4a727224a42aa7',
    messagingSenderId: '17739122534',
    projectId: 'reservation-5cd4b',
    authDomain: 'reservation-5cd4b.firebaseapp.com',
    storageBucket: 'reservation-5cd4b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz0OQkqcZJO7BGuOSKQLun76Zz0sx_tg8',
    appId: '1:17739122534:android:c40863bd5670985da42aa7',
    messagingSenderId: '17739122534',
    projectId: 'reservation-5cd4b',
    storageBucket: 'reservation-5cd4b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjgyXEtBEd26nOriPpTlJFimz9qWJUCGU',
    appId: '1:17739122534:ios:dea4e287641dcb13a42aa7',
    messagingSenderId: '17739122534',
    projectId: 'reservation-5cd4b',
    storageBucket: 'reservation-5cd4b.appspot.com',
    iosClientId: '17739122534-hn3dvkuj5dngeosh7jqta9q745isgq58.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservationTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBjgyXEtBEd26nOriPpTlJFimz9qWJUCGU',
    appId: '1:17739122534:ios:dea4e287641dcb13a42aa7',
    messagingSenderId: '17739122534',
    projectId: 'reservation-5cd4b',
    storageBucket: 'reservation-5cd4b.appspot.com',
    iosClientId: '17739122534-hn3dvkuj5dngeosh7jqta9q745isgq58.apps.googleusercontent.com',
    iosBundleId: 'com.example.reservationTest',
  );
}
